# Learn more about configuring your checkout UI extension:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2025-10"

[[extensions]]
name = "checkout-ui-product"
handle = "checkout-ui-product"
type = "ui_extension"
uid = "0e12e86b-a9ad-b0c9-0bef-256888fdd6cd678e5749"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/extension-targets-overview

[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.checkout.block.render"

[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration#api-access
api_access = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration#network-access
# network_access = true

# Loads metafields on checkout resources, including the cart,
# products, customers, and more. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration#metafields

# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_key"
# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_other_key"

# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration#settings-definition


# [[extensions.settings.fields]]
# key = "banner_title"
# type = "single_line_text_field"
# name = "Banner title"
# description = "Enter a title for the banner"

[extensions.settings]
[[extensions.settings.fields]]
key = "upsell_variant"
type = "variant_reference"
name = "Upsell Product"
description = "Select the product variant to show in checkout."

[[extensions.settings.fields]]
key = "custom_image_url"
type = "single_line_text_field"
name = "Custom Image URL"
description = "Paste a public image URL (optional)."

[[extensions.settings.fields]]
key = "title"
type = "single_line_text_field"
name = "Title"

[[extensions.settings.fields]]
key = "subtitle"
type = "single_line_text_field"
name = "Subtitle"

[[extensions.settings.fields]]
key = "description"
type = "multi_line_text_field"
name = "Description"

